1. จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4




In [7]:
import numpy as np

nArray0 = np.zeros(10)
print('array ที่มีแต่เลข 0 แบบ vector 10 ตัว')
print(nArray0)
print('array ที่มีแต่เลข 0 แบบ Matrix 4x4')
nArray044 = np.zeros((4,4))
print(nArray044)

array ที่มีแต่เลข 0 แบบ vector 10 ตัว
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array ที่มีแต่เลข 0 แบบ Matrix 4x4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3



In [2]:
nArray1 = np.ones(5)
print('array ที่มีแต่เลข 1 แบบ vector 5 ตัว')
print(nArray1)
print('array ที่มีแต่เลข 1 แบบ Matrix 3x3')
nArray133 = np.ones((3,3))
print(nArray133)

array ที่มีแต่เลข 1 แบบ vector 5 ตัว
[1. 1. 1. 1. 1.]
array ที่มีแต่เลข 1 แบบ Matrix 3x3
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง
4. ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

5. นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที



In [4]:
import random
import time
iMin, iMax = 10, 99

randomList = []
# Set a length of the list to 20
for i in range(1, 20):
    # any random numbers from 10 to 99
    randomList.append((iMax - iMin)*random.random()+iMin)
print(randomList)
# print(type(randomList))

[47.73528287746012, 50.678084243697086, 35.49440684712797, 29.882239833254015, 91.3865235662551, 64.53762826046733, 30.247551183264562, 24.280342256366534, 48.37923393121487, 49.81452259419709, 80.70452770636653, 97.31965083735984, 93.76676801390666, 34.060418739890025, 62.00120640020195, 59.44258094524328, 42.27462830704687, 54.92436661188488, 76.65570909092519]


In [13]:
npArray = np.array(randomList)
# print(npArrayRandom)
# print(type(npArray))

time1 = time.time()
x = npArray**2
print(x)
time2 = time.time()
timeOfNP = time2-time1

time1 = time.time()
y = [x ** 2 for x in randomList]
# print(type(y))
print(y)
time2 = time.time()
timeOfList = time2-time1
print('NP Used time ',timeOfNP)
print('List Used time ',timeOfList)

[2278.65723139 2568.26822261 1259.85291743  892.94825745 8351.49668953
 4165.10546149  914.91435258  589.53502009 2340.55027577 2481.48666129
 6513.22079231 9471.11443911 8792.20678377 1160.11212474 3844.14959508
 3533.42042943 1787.1441985  3016.68604772 5876.09773623]
[2278.6572313911374, 2568.268222611259, 1259.852917429445, 892.948257452113, 8351.496689525697, 4165.105461486271, 914.9143525842094, 589.5350200862983, 2340.550275771212, 2481.4866612877727, 6513.220792307684, 9471.114439105635, 8792.206783773789, 1160.1121247366516, 3844.1495950804433, 3533.420429431799, 1787.1441984989683, 3016.6860477167343, 5876.09773623255]
NP Used time  0.0005486011505126953
List Used time  0.00016355514526367188


6. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000 

In [15]:
print(np.arange(10,1001))

[  10   11   12   13   14   15   16   17   18   19   20   21   22   23
   24   25   26   27   28   29   30   31   32   33   34   35   36   37
   38   39   40   41   42   43   44   45   46   47   48   49   50   51
   52   53   54   55   56   57   58   59   60   61   62   63   64   65
   66   67   68   69   70   71   72   73   74   75   76   77   78   79
   80   81   82   83   84   85   86   87   88   89   90   91   92   93
   94   95   96   97   98   99  100  101  102  103  104  105  106  107
  108  109  110  111  112  113  114  115  116  117  118  119  120  121
  122  123  124  125  126  127  128  129  130  131  132  133  134  135
  136  137  138  139  140  141  142  143  144  145  146  147  148  149
  150  151  152  153  154  155  156  157  158  159  160  161  162  163
  164  165  166  167  168  169  170  171  172  173  174  175  176  177
  178  179  180  181  182  183  184  185  186  187  188  189  190  191
  192  193  194  195  196  197  198  199  200  201  202  203  204  205
  206 

7.จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000 

In [17]:
np.arange(10,2001,2)

array([  10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100,  102,  104,  106,  108,  110,  112,  114,  116,  118,
        120,  122,  124,  126,  128,  130,  132,  134,  136,  138,  140,
        142,  144,  146,  148,  150,  152,  154,  156,  158,  160,  162,
        164,  166,  168,  170,  172,  174,  176,  178,  180,  182,  184,
        186,  188,  190,  192,  194,  196,  198,  200,  202,  204,  206,
        208,  210,  212,  214,  216,  218,  220,  222,  224,  226,  228,
        230,  232,  234,  236,  238,  240,  242,  244,  246,  248,  250,
        252,  254,  256,  258,  260,  262,  264,  266,  268,  270,  272,
        274,  276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
        296,  298,  300,  302,  304,  306,  308,  3

8.จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

In [22]:
np.arange(13,900,2)

array([ 13,  15,  17,  19,  21,  23,  25,  27,  29,  31,  33,  35,  37,
        39,  41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,  63,
        65,  67,  69,  71,  73,  75,  77,  79,  81,  83,  85,  87,  89,
        91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111, 113, 115,
       117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141,
       143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
       169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193,
       195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219,
       221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245,
       247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271,
       273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297,
       299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323,
       325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349,
       351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 371, 37

9.จงสร้าง identity matrix แบบ 4x4

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

10.จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

In [24]:
np.linspace(5,25,100)

array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
        6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
        7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
        8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
        9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
       10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
       11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
       12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
       13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
       14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
       15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
       16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
       17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
       18.13131313, 18.33333333, 18.53535354, 18.73737374, 18.93

11.จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

In [25]:
np.random.rand()

0.7165724000197999

12.จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [29]:
matrix1 = np.random.randint(50,100,(4,4))
print(matrix1)
matrix1.T

[[90 80 70 76]
 [72 97 71 91]
 [64 82 54 94]
 [90 71 75 81]]


array([[90, 72, 64, 90],
       [80, 97, 82, 71],
       [70, 71, 54, 75],
       [76, 91, 94, 81]])

In [36]:
arr2d = np.array([[1,2,3,4,5],
       [6,7,8,9,10],
       [11,12,13,14,15],
       [16,17,18,19,20],
       [21,22,23,24,25]])
print(arr2d)
arr2d.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


(5, 5)

13.ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14

In [52]:
arr2d[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

14.ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

In [54]:
arr2d[3,2:]

array([18, 19, 20])

15.ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

In [57]:
arr2d[3:,:2]

array([[16, 17],
       [21, 22]])

16.ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

In [60]:
arr2d[2]

array([11, 12, 13, 14, 15])

17.จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

In [33]:
print(np.array([[1,2,3,4,5],
       [6,7,8,9,10],
       [11,12,13,14,15],
       [16,17,18,19,20],
       [21,22,23,24,25]]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


18.จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า
      50 และปริ้นออกมา


In [83]:
arr2d = np.random.randint(10,100,(5,5))
print(arr2d)
for x in arr2d:
  for y in x:
    if y > 50:
        print(y)

[[73 80 10 69 76]
 [91 96 73 88 84]
 [34 81 92 41 43]
 [30 27 76 68 39]
 [72 50 97 69 43]]
73
80
69
76
91
96
73
88
84
81
92
76
68
72
97
69


19.จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่า  
      มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

In [84]:
arr2d = np.random.randint(10,100,(5,5))
print(arr2d)
boolArr = arr2d > 40
arr2d[boolArr]

[[28 47 83 62 69]
 [64 64 72 41 21]
 [39 48 96 51 63]
 [46 61 39 64 38]
 [73 73 58 45 35]]


array([47, 83, 62, 69, 64, 64, 72, 41, 48, 96, 51, 63, 46, 61, 64, 73, 73,
       58, 45])

20.เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 
      3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

In [105]:

lst = []
# print (lst)
vInput2 = 0
while (len(lst)<=9):
    vInput2 = int(input('Input ที่ '+str(len(lst)+1)+' (10 - 100) :'))
    if( vInput2 >= 10 and vInput2 <= 100):
        if (vInput2 not in lst):
            lst.append(vInput2)
            if(len(lst)==9):
                break;

print(lst)

Input ที่ 1 (10 - 100) :10
Input ที่ 2 (10 - 100) :10
Input ที่ 2 (10 - 100) :11
Input ที่ 3 (10 - 100) :11
Input ที่ 3 (10 - 100) :11
Input ที่ 3 (10 - 100) :99
Input ที่ 4 (10 - 100) :34
Input ที่ 5 (10 - 100) :35
Input ที่ 6 (10 - 100) :36
Input ที่ 7 (10 - 100) :37
Input ที่ 8 (10 - 100) :38
Input ที่ 9 (10 - 100) :39
[10, 11, 99, 34, 35, 36, 37, 38, 39]


In [116]:
arr2D = np.array(lst)
print(arr2D)
arr2D = arr2D.reshape(3,3)
print(arr2D)
arr2D = arr2D.T
print(arr2D)
print(arr2D[2,2])

[10 11 99 34 35 36 37 38 39]
[[10 11 99]
 [34 35 36]
 [37 38 39]]
[[10 34 37]
 [11 35 38]
 [99 36 39]]
39
